### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by inukshuk** [inukshuk/wapiti-ruby#3]
Try to add this workaround in ext/wapiti/model.h:33

```
#ifndef _WIN32
#include <sys/time.h>
#endif
```

**Comment by pilmus** [comment]
Hey, do you happen to still be working on resolving this? It would be great to use the parser on windows machines!

Currently, when trying to build the gem I get the following error:

```shell
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing wapiti:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/ext/wapiti
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20170325-8340-oxcws9.rb extconf.rb
checking for main() in -lpthread... yes
checking for main() in -lm... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/wapiti-0.1.1/mkmf.log

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/ext/wapiti
make "DESTDIR=" clean

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/ext/wapiti
make "DESTDIR="
generating native-x64-mingw32.def
compiling bcd.c
compiling decoder.c
compiling gradient.c
compiling lbfgs.c
lbfgs.c: In function 'trn_lbfgs':
lbfgs.c:107:4: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:107:4: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:107:4: warning: too many arguments for format [-Wformat-extra-args]
lbfgs.c:110:5: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:110:5: warning: too many arguments for format [-Wformat-extra-args]
lbfgs.c:112:5: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:112:5: warning: too many arguments for format [-Wformat-extra-args]
lbfgs.c:317:4: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:317:4: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:317:4: warning: too many arguments for format [-Wformat-extra-args]
lbfgs.c:319:5: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:319:5: warning: unknown conversion type character 'a' in format [-Wformat]
lbfgs.c:319:5: warning: too many arguments for format [-Wformat-extra-args]
compiling model.c
model.c: In function 'mdl_save':
model.c:275:4: warning: unknown conversion type character 'a' in format [-Wformat]
model.c:275:4: warning: too many arguments for format [-Wformat-extra-args]
model.c: In function 'mdl_load':
model.c:301:3: warning: unknown conversion type character 'a' in format [-Wformat]
model.c:301:3: warning: too many arguments for format [-Wformat-extra-args]
compiling native.c
In file included from c:/Ruby23-x64/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from c:/Ruby23-x64/include/ruby-2.3.0/ruby/ruby.h:36,
                 from c:/Ruby23-x64/include/ruby-2.3.0/ruby.h:33,
                 from native.h:4,
                 from native.c:14:
c:/Ruby23-x64/include/ruby-2.3.0/ruby/win32.h:294:12: error: conflicting types for 'gettimeofday'
In file included from model.h:33:0,
                 from decoder.h:36,
                 from native.c:6:
c:\ruby23-x64\devkit\mingw\bin\../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/sys/time.h:42:13: note: previous declaration of 'gettimeofday' was here
make: *** [native.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/wapiti-0.1.1/gem_make.out
```

Please let me know if there are any steps I could try, or information I can provide.

**Comment by inukshuk** [comment]
I'm not currently working on this, unfortunately.

If you want to give this a try, it should not be much that is missing to compile wapiti on Windows. The POSIX `gettimeofday` function is used [here](https://github.com/inukshuk/wapiti-ruby/blob/18a5c469ada2c51cbbf32d96fcf02cfc2b8116ce/ext/wapiti/progress.c#L133) -- this does not seem to be available on Windows / MinGW. We'd either have to check if POSIX `gettimeofday` is available in a Windows environment or, otherwise, use a suitable Windows alternative.

**Comment by pilmus** [comment]
Hi,

Thank you for your quick response! I'm afraid I'm very (*very*) new to
Ruby, so I'm not sure how to go about changing the code in such a way that
it will work. It seems that the windows alternative for gettimeofday() is
GetLocalTime(), but when I change the progress.c file and run "gem install
wapiti" the file is automatically changed back.

I understand if this is not a high priority for you, but any pointers would
be more than welcome!

2017-03-26 13:04 GMT+02:00 Sylvester Keil <notifications@github.com>:

**Comment by WouterJeuris** [comment]
Hey. I know nothing about Ruby, nothing about Gems, and nothing about Cygwin, but...

There seem to be other posts (mostly on StackExchange) out there that face this error, and some seem to suggest that time.h and WinGW have something to do with it...

When I comment out the gettimeofday function in time.h (found this in the ruby development kit mingw directory) the error changes into this one: http://stackoverflow.com/questions/12747515/installing-compiling-in-cygwin-mingw-how-to-set-the-include-path-symbolic

Of course, I don't know if I fixed something or just broke it even more :)
I'll dig deeper... Just hope I can get Anystyle parser to work. It looks like a very very useful piece of code...

**Comment by inukshuk** [comment]
I'm sorry I haven't had more time to look at this. If I remember correctly we're not even exposing the progress updates to the Ruby API so we could also try to simply disable that part completely for the Windows build.

**Comment by WouterJeuris** [comment]
There's never a need for sorry's on free OpenSource projects :)
Thanks you for making this code available.

That being said, *if* you find the time to get the Windows build to work... that would save me the time of having to learn Ruby and try and fix it myself :) 

I work at a research group in Belgium that does Bibliometric analysis, and have developed a long list of Regular Expressions over the past few years to do Reference Parsing. Yet, I was now looking for something more sophisticated. Anystyle, ParsCit and FreeCite caught my attention, but my preference went to Anystyle since ParsCit and FreeCite seem to be last worked on in 2013/2009, and Anystyle can be trained with our own datasets, which seems like a great added bonus.

If it can serve as a motivation, if this works on Windows, I'll probably be using it for the years to come... (and hopefully make some minor contributions in terms of training sets or code...)

**Comment by a-fent** [comment]
Just a note to say that I was able to install Anycite on Windows using [MSYS2 ](url)and the Ruby which that provides. In the MSYS2 (not MingW) shell that comes with that, I did something like

  `pacman -Su ruby`
  `pacman -Su msys2-devel gmp gmp-devel libcrypt libcrypt-devel`

And then `gem install anycite-parser`. Maybe some other packages are needed that I already had previously installed.

Unfortunately the parser then doesn't work, failing on  `/h/.gem/ruby/2.3.0/gems/wapiti-0.1.1/lib/wapiti/model.rb:25:in 'load': failed to load model: failed to open model file (Wapiti::NativeError)`

I suspect this is in mdl_load in Wapiti's [model.c](https://github.com/inukshuk/wapiti-ruby/blob/master/ext/wapiti/model.c#L287), where the code's expecting something other than provided in the model file bundled with Anycite, poss. either with the line-endings on Windows or with the format string `SCNu64`.

**Comment by WouterJeuris** [comment]
I've been playing around with this, and managed to get up to the same point as a-fent got.
Here is an updated version of the "HOWTO" a-fent provided

* Install MSYS2
  * http://www.msys2.org/
* Install all the updates 
  * pacman -Syu
  * pacman -Su
* Install ruby and other suggestions by a-fent
  * pacman -Su ruby
* make changes to path, as suggested by ruby installer
  * PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"
* Install other suggestions by a-fent
  * pacman pacman -Su msys2-devel gmp gmp-devel libcrypt libcrypt-devel
* Install make
  * pacman -Su make
* Install anystyle-parser (i think anycite-parser was a typo on a-fents part, don't think it exists)
  * gem install anystyle-parser
* I've also tried installing kyotocabinet-ruby, but this caused an error
  * *** extconf.rb failed *** Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

Then run a little test
```
$ irb
> require 'anystyle/parser'
> Anystyle.parse 'just a test'
```

```
Wapiti::NativeError: invalid model format
        from /usr/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/lib/wapiti/model.rb:25:in `load'
        from /usr/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/lib/wapiti/model.rb:25:in `load'
        from /usr/lib/ruby/gems/2.3.0/gems/wapiti-0.1.1/lib/wapiti/utility.rb:10:in `load'
        from /home/u0059885/.gem/ruby/2.3.0/gems/anystyle-parser-0.8.2/lib/anystyle/parser/parser.rb:66:in `reload'
        from /home/u0059885/.gem/ruby/2.3.0/gems/anystyle-parser-0.8.2/lib/anystyle/parser/parser.rb:60:in `initialize'
        from /home/u0059885/.gem/ruby/2.3.0/gems/anystyle-parser-0.8.2/lib/anystyle/parser/parser.rb:44:in `new'
        from /home/u0059885/.gem/ruby/2.3.0/gems/anystyle-parser-0.8.2/lib/anystyle/parser/parser.rb:44:in `instance'
        from /home/u0059885/.gem/ruby/2.3.0/gems/anystyle-parser-0.8.2/lib/anystyle/parser/utility.rb:4:in `parse'
        from (irb):2
        from /usr/bin/irb:11:in `<main>'
```

I'll keep this post updated if I find a solution.

**Comment by inukshuk** [comment]
I'll also finally have time to look at this in the next couple of weeks. We'll get it done! : )

**Comment by a-fent** [comment]
I have Wapiti compiling and working on Windows using either/both of the MSYS2 and MingW64 toolchain and ruby (the latter is *much* faster). 

There are a number of small problems with the file format and inclusion of headers. The main difficulty is that sprintf on Windows does not (it seems) support the %la format (even though this is C99 standard), and this is used by Wapiti to serialise floats in models. I have just used %le instead. But this introduces an incompatibility. So for Anystyle, the model must be trained from scratch, the supplied .mod file cannot be read by Windows.

There's a number of changes and fixes to Anystyle to, I've put these on gitlab repositories: 
https://gitlab.com/a_fent/wapiti/edit
https://gitlab.com/a_fent/anycite/edit  (...yes, I did mistype the name)

**Comment by WouterJeuris** [comment]
a-fent has been helping me to get Wapiti and Anystyle Parser to work on Windows.
Going from a vanilla environment to a working Anystyle Parser was not so straightforward for me as a non-Ruby developer. So I'd like to leave this little howto here for anyone else trying this. My guess is that this is still an inefficient/unusual way of doing this, and the terminology might be a bit off but... it works :)

## Optional
  - To avoid conflicts, uninstall any Shells (MSYS, mingw-64) and Ruby installations, and remove any mentions from your Windows Environment variables. If you know what you are doing, this is not necessary. Just keep in mind that you might need to change your path variables to point them to the correct GCC toolchain and Ruby version.
  - Matthieu Vachon posted a great introduction into MSYS, mingw64, Shells, ... [here](https://sourceforge.net/p/msys2/discussion/general/thread/dcf8f4d3/). I can highly recommend reading this if you are not a Ruby developer.

## Prepare the environment
- Install [MSYS2](http://www.msys2.org/)
  - I used the 64bit version (version 20161025) and installed to C:\msys64
	
- Open the MSYS2 Shell (For me the shortcut was called "MSYS2 MinGW 64-bit")	
- Bring MSYS2 up to date. Important, otherwise you can only install Ruby 2.3, and not 2.4.
  - `pacman -Syu`
  - Close and open the Shell
  - `pacman -Syu`
		
- Install the GCC Toolchain: Needed to "rake" the packages later
  - `pacman -S mingw-w64-x86_64-toolchain`
- Install Ruby, git and make: Needed to clone the git repo and use "bundler install"
  - `pacman -S mingw-w64-x86_64-ruby`
  - `pacman -S git`
  - `pacman -S make`

- Install Bundler: this makes the command line tool "bundler" available
  - `gem install bundler`

## Set up Wapiti and Anystyle Parser
- Git clone the projects containing the Windows fixed versions of Wapiti and Anystyle Parser 
  - You will need a Gitlab account
  - Just downloading the source will get you in trouble later on, since you won't be able to use "bundle install"
  - Go to a directory where you want to clone the projects to. Folders will be created
  - `git clone https://gitlab.com/a_fent/wapiti.git`
  - `git clone https://gitlab.com/a_fent/anycite.git`

- Native Compile Wapiti, create the gem, and install it
  - go inside wapiti directory
  - `bundler install`
  - `bundle exec rake`
  - gem build wapiti.gemspec
  - gem install wapiti-0101.gem

- Install Anystyle Parser dependencies
  - Using bundle install on anystyle parser doesn't seem to work, so we need to install the dependencies manually
  - `gem install bibtex-ruby builder namae`

## Using Anystyle Parser
- Go to the folder containing the "anycite" folder.
- Copy `anystyle.mod` to this directory. You can find this here (./anycite/lib/anystyle/parser/support)
- Create a text file (eg. test.rb) and add the following lines:
		`$:.unshift("./anycite/lib/")`
		`require "anystyle/parser"`
		`pars = Anystyle::Parser::Parser.new(:model=> "anystyle.mod")`
		`print pars.model.labels`
		`print pars.parse('Poe, Edgar A. Essays and Reviews. New York: Library of America, 1984.', :bibtex).to_s`
- `ruby test.rb`

## Known issues
... post whatever issue you are facing :) I feel like I've seen every possible error message while trying to get this to work. I can probably tell you what's going wrong.

Many many thanks to Sylvester for making these tools, and to a-fent for providing the Windows fix!

**Comment by inukshuk** [comment]
@a-fent @WouterJeuris awesome work!

I finally have the time to dust-off the wapiti and anystyle gems and thanks to you we now have a first green [windows build](https://ci.appveyor.com/project/inukshuk/wapiti-ruby/branch/master). I decided to remove most of the progress reporting so the `sys/time` includes are not required anymore for the time being. That leaves the model format issue; I'm considering switching to `%le` by default so that don't have to manage two different model formats.

I have a few more changes planned for wapiti and then I'll update anystyle-parser.

**Comment by a-fent** [comment]
@inukshuk Great! Just to mention that the other issue I ran into was that the pre-prepared model supplied with Anystyle started with a Byte-Order-Mark, and for whatever reason Windows didn't like this.

It means that the first call to `fscanf` in `load_model` choked here: https://github.com/inukshuk/wapiti-ruby/blob/master/ext/wapiti/model.c#L286

 I haven't tried moving models trained on Windows to Linux or vice-versa yet, but it's something else that may affect portability if you want to ship Wapiti models within packages.
